---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: macosx1011

suites:
  - name: default
    run_list:
      - recipe[macos_configuration::default]
    # verifier:
    #   inspec_tests:
    #     - test/recipes
    attributes:
